
import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileWriter;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MAHE
 */
public class tradepage extends javax.swing.JFrame {
    String accno;
    int check=1;
    /**
     * Creates new form tradepage
     */
    public tradepage() {
        initComponents();
    }
    
    public tradepage(String acno){
        accno=acno;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Trade Page");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 7, 147, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Company Symbol: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 58, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 58, 149, 29));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 42, 303, 10));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Transaction");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 134, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buy", "Sell" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 134, 65, 28));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Quantity");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 180, -1, 29));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 180, 65, 29));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 58, -1, 29));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 230, 120, 28));
        jLabel1.getAccessibleContext().setAccessibleParent(jButton1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 250, 28));

        label1.setBackground(new java.awt.Color(255, 255, 255));
        label1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label1.setText("COMPANY STOCK:");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 209, -1));

        jButton2.setText("Confirm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 140, 29));

        jButton3.setText("Search by Company");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 58, -1, 29));

        jButton4.setText("Go Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 0, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\MAHE\\Desktop\\stock gifs\\new gifs\\giphy (6).gif")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 450, 250));

        jButton5.setText("Expert Advice");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\MAHE\\Desktop\\stock gifs\\new gifs\\coolbg1.png")); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 750, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                        // TODO add your handling code here:
                        check=0;
                        String h=jTextField1.getText();
                        String gen="";
                        for(int i=0;i<h.length();i++)
                        {
                            gen=gen+h.substring(i,i+1).toUpperCase();
                           
                        }
                        gen=gen+h.substring(h.length()-1,h.length()-1).toUpperCase();
                        try{
           label1.setText(gen+" STOCK:");                
           FileWriter fw=new FileWriter("C:\\Users\\MAHE\\Desktop\\store.html");
           fw.write(h);
           fw.close();
           
           FileWriter fw1=new FileWriter("C:\\Users\\MAHE\\Desktop\\stpe.html");
           fw1.write(h);
           fw1.close();
           
           String co = "python C:\\Users\\MAHE\\extract_stpr.py";
           String stpr="python C:\\Users\\MAHE\\extr_perc.py";
           Process p = Runtime.getRuntime().exec(co);
           BufferedReader in = new BufferedReader(new InputStreamReader(p.getInputStream()));
           
           
           jLabel1.setText(in.readLine());
           in.close();
           Process s=Runtime.getRuntime().exec(stpr);
           BufferedReader in2 = new BufferedReader(new InputStreamReader(s.getInputStream()));
           String k = in2.readLine();
           
           
           if(k.charAt(0)=='+')
           {
               jLabel3.setForeground(new java.awt.Color(51, 204, 0));
           }
           
           else if(k.charAt(0)=='-')
           {
                   jLabel3.setForeground(Color.red);
                   }
           else
           {
               jLabel3.setForeground(Color.black);
           }
           
           jLabel3.setText(k);
         
           in2.close();
           
           
          
                
       }
       catch(Exception e)
       {}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String symb=jTextField1.getText();
        String nu="";
        String j="";
        int qty;
        if(symb.equals(nu) || (jTextField3.getText()).equals(nu))
        {
           JOptionPane.showMessageDialog(null,"Fields are missing","Warning", JOptionPane.WARNING_MESSAGE); 
        }
        else{
           if(jTextField3.getText().equals(nu))
           {
               qty=1;
           }
           else{
            qty=Integer.parseInt(jTextField3.getText());
           }
           
           if(qty<0)
           {
               JOptionPane.showMessageDialog(null,"Quantity can't be negative","Warning", JOptionPane.WARNING_MESSAGE); 
           }
           else{   
        double shpr=1;
        String tran=jComboBox1.getSelectedItem().toString();
        String b="Buy";
        String s="Sell";
        int check2=1;
        
        
        
        if(check==1)
        {
            try{
            FileWriter fw=new FileWriter("C:\\Users\\MAHE\\Desktop\\store.html");
            fw.write(symb);
            fw.close();
            
            String co = "python C:\\Users\\MAHE\\extract_stpr.py";
            Process p = Runtime.getRuntime().exec(co);
            BufferedReader in = new BufferedReader(new InputStreamReader(p.getInputStream()));
            j=in.readLine();
            if(j.equals(""))
            {
               JOptionPane.showMessageDialog(null,"No internet connection","Warning", JOptionPane.WARNING_MESSAGE); 
            }
           
            String prcheck="Invalid Symbol";
            if(j.equals(prcheck))
            {
                JOptionPane.showMessageDialog(null,"Invalid Symbol","Warning", JOptionPane.WARNING_MESSAGE);
            }
            else{
            shpr=Double.parseDouble(j);
            }
            }
            
            
            catch(Exception e)
            {
                
            }
            
        }
        
        else
        {
            j=jLabel1.getText();
            String prcheck="Invalid Symbol";
            if(j.equals(prcheck))
            {
                JOptionPane.showMessageDialog(null,"Invalid Symbol","Warning", JOptionPane.WARNING_MESSAGE);
            }
            else{
            shpr=Double.parseDouble(j);
            }
            
            
        }
        check=1;
        if(!j.equals("Invalid Symbol"))
        {    
        double tot=shpr*qty;
        
        try{
            
            Class.forName("com.mysql.jdbc.Driver"); 
            String dbURL = "jdbc:mysql://localhost:3306/testdb";
            Connection con = DriverManager.getConnection(dbURL,"root","");
            if (con != null) {
                    Statement stmt = con.createStatement() ;
                    Statement stmt1 = con.createStatement() ;
                    
                    if(tran.equals(b))
                    {
                    ResultSet rs = stmt.executeQuery( "SELECT balance FROM users where acc_no="+accno+";") ;
                    while(rs.next())
                    {
                    double bal=Double.parseDouble(rs.getString(1));
                    
                    if(bal>=tot)
                    {
                        ResultSet rd=stmt1.executeQuery("select sym from buy where acc_no="+accno);
                        while(rd.next())
                        {
                         
                        if(rd.getString(1).equals(symb)){
                        stmt.executeUpdate("update users set balance=balance-"+tot+" where acc_no="+accno);
                        stmt.executeUpdate("update buy set qty=qty+"+qty+" where acc_no="+accno+" and sym='"+symb+"'");
                        stmt.executeUpdate("update buy set tot=tot+"+tot+" where acc_no="+accno+" and sym='"+symb+"'");
                        JOptionPane.showMessageDialog(null,"Success: SHARES HAVE BEEN BOUGHT","Success", JOptionPane.INFORMATION_MESSAGE);
                        try{
                        FileWriter fw=new FileWriter("C:\\Users\\MAHE\\Desktop\\qty.html");
                        fw.write(""+qty);
                        fw.close();
                        
                        String send="python C:\\Users\\MAHE\\smsinfo.py";
                        Process p = Runtime.getRuntime().exec(send);

                        }
                        catch(Exception e)
                        {
                            
                        }
                        check2=0;
                        break;
                        }
                  
                        }
                        if(check2==1)
                        {
                            stmt1.executeUpdate("insert into buy values(null,'"+symb+"',"+accno+","+qty+","+tot+",'"+b+"')");
                            stmt.executeUpdate("update users set balance=balance-"+tot+" where acc_no="+accno);
                            JOptionPane.showMessageDialog(null,"Success: SHARES HAVE BEEN BOUGHT","Success", JOptionPane.INFORMATION_MESSAGE);
                            try{
                        FileWriter fw=new FileWriter("C:\\Users\\MAHE\\Desktop\\qty.html");
                        fw.write(""+qty);
                        fw.close();
                        
                        String send="python C:\\Users\\MAHE\\smsinfo.py";
                        Process p = Runtime.getRuntime().exec(send);

                        }
                        catch(Exception e)
                        {
                            
                        }

                        }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"You don't have sufficient funds","Warning", JOptionPane.WARNING_MESSAGE);
                    }
                    }
                    }
                    else
                    {
                        ResultSet rs = stmt.executeQuery("select qty from buy where sym='"+symb+"' and acc_no="+accno);
                        
                        if(rs.next())
                        {
                            if (qty<=Integer.parseInt(rs.getString(1)))
                            {
                                try{
                                    FileWriter fw=new FileWriter("C:\\Users\\MAHE\\Desktop\\qty.html");
                                    fw.write(""+qty);
                                    fw.close();
                        
                                    String send="python C:\\Users\\MAHE\\smsinfos.py";
                                    Process p = Runtime.getRuntime().exec(send);

                                }
                                catch(Exception e)
                                {
                                    System.out.println("Exception");
                                }
                                stmt.executeUpdate("update users set balance=balance+"+tot+" where acc_no="+accno);
                                JOptionPane.showMessageDialog(null,"Success: SHARES HAVE BEEN SOLD","Success", JOptionPane.INFORMATION_MESSAGE);
                                stmt.executeUpdate("update buy set qty=qty-"+qty+" where acc_no="+accno+" and sym='"+symb+"'");
                                
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(null,"You don't have enough shares to sell.","Warning", JOptionPane.WARNING_MESSAGE);
                            }
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null,"You don't have shares of the company.","Warning", JOptionPane.WARNING_MESSAGE);
                        }
                        
                    }
                    
            }
            }     
        
        catch(ClassNotFoundException e)
        {
            e.printStackTrace();
        }
       catch (SQLException ex) {
            ex.printStackTrace();
        }
        }
        }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new compcheck().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new expert().setVisible(true);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tradepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tradepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tradepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tradepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tradepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
